#!/bin/env ruby
# encoding: utf-8

create_table "users", force: :cascade do |t|
  t.string "name"
  t.string "email", null: false
  t.string "password_digest", null: false
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
  t.index ["email"], name: "index_users_on_email", unique: true
end

create_table "consume_items", force: :cascade do |t|
  t.string "name"
  t.integer "kind"
  t.bigint "itemable_id"
  t.string "itemable_type"
  t.timestamps
end

create_table "weapon_items", force: :cascade do |t|
  t.string "name"
  t.integer "kind"
  t.bigint "itemable_id"
  t.string "itemable_type"
  t.timestamps
end

create_table :treasure_boxes do |t|
  t.bigint :item_group_id, foreign_key: true
end

create_table :item_groups do |t|
end

create_table :item_group_lottery_machines do |t|
  t.bigint :item_group_id, foreign_key: true
  t.integer :item_quantity
  t.string :item_type
  t.bigint :item_id
  t.float :weight
end
