#!/bin/env ruby
# encoding: utf-8

create_table "users", force: :cascade do |t|
  t.string "name"
  t.string "email", null: false
  t.string "password_digest", null: false
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
  t.index ["email"], name: "index_users_on_email", unique: true
end
